/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_MvU7775u7",
    "aws_user_pools_web_client_id": "1tnk20jc358mftsfsram3tsug8",
    "oauth": {
        "domain": "four-o-four-plant-app.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "openid",
            "profile"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": []
};


export default awsmobile;
